extends:
  - pegasus
  - plugin:eslint-plugin/recommended

plugins:
  - file-progress
  - eslint-plugin

rules:
  file-progress/activate: 1
settings:
  progress:
    hide-progress: false
    success-message: "Lint done..."
    fail-message: "Lint done with errors."

env:
  node: true
